// <auto-generated />
namespace MyFilterBubble.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FeedItem_Classification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FeedItem_Classification));
        
        string IMigrationMetadata.Id
        {
            get { return "201703211956200_FeedItem_Classification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
