// <auto-generated />
namespace MyFilterBubble.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Feed_and_FeedItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Feed_and_FeedItems));
        
        string IMigrationMetadata.Id
        {
            get { return "201703191655000_Feed_and_FeedItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
